# Generated by Django 6.0.1 on 2026-01-31 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=255)),
                ('CategoryDescription', models.TextField()),
                ('CreationDate', models.DateTimeField(auto_now_add=True)),
                ('UpdationDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=255)),
                ('ProductPrice', models.FloatField()),
                ('ProductDiscountPrice', models.FloatField()),
                ('ShortDescription', models.TextField()),
                ('LongDescription', models.TextField()),
                ('ProductImage1', models.ImageField(upload_to='products/productsimages/')),
                ('ProductImage2', models.ImageField(upload_to='products/productsimages/')),
                ('ProductImage3', models.ImageField(upload_to='products/productsimages/')),
                ('ProductFile', models.FileField(upload_to='products/productsFile/')),
                ('CreationDate', models.DateTimeField(auto_now_add=True)),
                ('UpdationDate', models.DateTimeField(auto_now_add=True)),
                ('DemoFolder', models.CharField(blank=True, help_text='Auto-generated demo folder name', max_length=255)),
                ('CategoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
    ]
