# Generated by Django 6.0.1 on 2026-03-06 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_database_product_demourl_product_features_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='DemoURL',
        ),
        migrations.AddField(
            model_name='product',
            name='PreviewFile',
            field=models.FileField(blank=True, null=True, upload_to='products/preview/'),
        ),
    ]
