# Generated by Django 6.0.1 on 2026-03-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_demourl_product_previewfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='DemoVideo',
            field=models.FileField(blank=True, null=True, upload_to='products/demo_videos/'),
        ),
    ]
