# Generated by Django 6.0.1 on 2026-03-07 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_demovideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='installVideo',
            field=models.FileField(blank=True, null=True, upload_to='products/install_videos/'),
        ),
    ]
