# Generated by Django 6.0.1 on 2026-03-07 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_installvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='installVideo',
        ),
    ]
