# Generated by Django 6.0.1 on 2026-03-12 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productlesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.clientuser')),
            ],
            options={
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
