# Generated by Django 6.0.1 on 2026-03-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_lessonprogress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productlesson',
            options={},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='CategoryId',
            new_name='Category',
        ),
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='products/certificates/'),
        ),
    ]
