# Generated by Django 6.0.1 on 2026-03-18 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_productlesson_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='CategoryId',
        ),
    ]
