# Generated by Django 6.0.1 on 2026-04-08 10:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_rename_category_product_categoryid'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='phone_number',
            field=models.CharField(default=1, max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (e.g. 9876543210 or +919876543210)', regex='^\\+?91?\\d{10}$')]),
            preserve_default=False,
        ),
    ]
