# Generated by Django 6.0.1 on 2026-04-08 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_clientuser_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientuser',
            name='phone_number',
        ),
    ]
