# Generated by Django 6.0.1 on 2026-04-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
